import { IProblem } from '../../app.component.model';
import { Helper } from 'src/app/utils/helper';

export class P12 implements IProblem {
    public title = 'Problem 12';
    public description =
        'The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:' +
        '\n1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...' +
        '\nLet us list the factors of the first seven triangle numbers:' +
        '\n1: 1' +
        '\n3: 1,3' +
        '\n6: 1,2,3,6' +
        '\n10: 1,2,5,10' +
        '\n15: 1,3,5,15' +
        '\n21: 1,3,7,21' +
        '\n28: 1,2,4,7,14,28' +
        '\nWe can see that 28 is the first triangle number to have over five divisors.' +
        '\nWhat is the value of the first triangle number to have over five hundred divisors?';

    getAnswer(): string {
        let result = 0;

        let i = 1;
        let numberOfDivisors = 1;
        while (numberOfDivisors <= 500) {
            result += i;
            numberOfDivisors = Helper.numberOfDivisors(result);
            i++;
        }

        return result.toString();
    }
}
