import { IProblem } from '../../app.component.model';

export class P44 implements IProblem {
  public title = 'Problem 44';
  public description = 'Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:' +
                        '\n1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...' +
                        '\nIt can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.' +
                        '\nFind the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?';

  getAnswer(): string {
    // performance is ~1 second when running the unit test. Not great, not terrible.
    let result = 0;
    const pentagonals: number[] = [];
    let iterator = 1000;
    let searching = true;
    while (searching) {
      iterator++;
      const sum = Math.floor((3 * iterator * iterator - iterator) / 2);
      pentagonals.forEach((pj: number) => {
        if (pentagonals.indexOf(sum - pj) > -1 && pentagonals.indexOf(sum - (2 * pj)) > -1) {
          result = sum - (2 * pj);
          searching = false;
        }
      });
      pentagonals.push(sum);
    }

    return result.toString();
  }
}
