import { IProblem } from '../../app.component.model';

export class P45 implements IProblem {
  public title = 'Problem 45';
  public description = 'Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:' +
                        '\nTriangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...' +
                        '\nPentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...' +
                        '\nHexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...' +
                        '\nIt can be verified that T285 = P165 = H143 = 40755.' +
                        '\nFind the next triangle number that is also pentagonal and hexagonal.';

  getAnswer(): string {
    // Hexagonal numbers are in the same range as Triangle numbers so we just have to find Pn=Hn
    let result = 0;

    let j = 166;
    let k = 144;
    let keepSearching = true;
    while (keepSearching) {
      const pentagon = j * (j * 3 - 1) / 2;
      const hexagon  = k * (k * 2 - 1);
      const min = Math.min(pentagon, hexagon);
      if (min === pentagon && min === hexagon) {
        keepSearching = false;
        result = min;
      }
      if (min === pentagon) j++;
      if (min === hexagon ) k++;
    }

    return result.toString();
  }
}
