export interface IProblem {
  title: string;
  description: string;
  answer: number;
}

export const PROBLEMS: IProblem[] = [
  {
    title: 'Problem 1',
    description: 'If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.' +
                  '\nFind the sum of all the multiples of 3 or 5 below 1000.',
    answer: 1
  },
  {
    title: 'Problem 2',
    description: 'Each new term in the Fibonacci sequence is generated by adding the previous two terms. ' +
                  '\nBy starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... ' +
                  '\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.',
    answer: 2
  }
];
